#!/usr/bin/env bash
# A Bash script that configures an Ubuntu server with the below requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

# create backup
cp /etc/hosts hosts

cp /etc/hosts hosts.new

# if there's an entry for localhost, replace it. Otherwise add new entry
if grep -q 'localhost$' hosts.new
then
	sed -i 's/.*localhost/127.0.0.2	localhost/g' hosts.new
else
	echo '127.0.0.2	localhost' >> hosts.new
fi

# if there's an entry for facebook.com, replace it. Otherwise add new entry
if grep -q 'facebook.com$' hosts.new
then
	sed -i 's/.*facebook.com/8.8.8.8	facebook.com/g' hosts.new
else
	echo '8.8.8.8	facebook.com' >> hosts.new
fi

cp -f hosts.new /etc/hosts
