#!/usr/bin/env bash
# A Bash script that runs Apache on a docker container and returns
# a page containing Hello Holberton when querying the root of it.

echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart
